# playbook defines a set of tasks to be run on hosts.
-
  name: playbook demo
  hosts: localhost
  vars:
      file_name: inventory

  # create tasks (list of dictionaries).
  tasks:
    # a tasks is an action to be performed on the hosts.
    - name: Fetch resources and write in the file
      fetch_resources:
        url: https://www.google.com
        dest: /tmp/testAnsible.txt