-
  name: hdfs playbook
  hosts: yum_hosts
  tasks:
    # Install requirements
    - name: Install yum requirements
      become: yes
      raw: yum install -y gcc openssl-devel python-devel libffi libffi-devel

    - name: Install hdfs and kerberos modules
      become: yes
      pip:
        name: "{{ item }}"
        extra_args: --trusted-host files.pythonhosted.org --trusted-host pypi.org --trusted-host pypi.python.org
      with_items:
        - hdfs
        - requests-kerberos
        - pykerberos

    - name: creates new directory in hdfs if not exists
      hdfs_operations:
        webhdfs_url: http://sandbox.hortonworks.com:50070
        path: /tmp/new-folder
        command: mkdir
      register: result_mkdir

    - name: dump output for mkdir
      debug:
        msg: '{{ result_mkdir }}'