-
  name: hdfs playbook
  hosts: ubuntu_hosts
  tasks:
    - name: Install ubuntu packages
      become: yes
      raw: apt-get -y install gcc libkrb5-dev

    # Install hdfs python library
    - name: Install hdfs module
      become: yes
      pip:
        name: hdfs
        state: latest

    - name: sets owner of the hdfs file or directory
      hdfs_operations:
        webhdfs_url: http://sandbox.hortonworks.com:50070
        path: /tmp/kernel_cleaner.sh
        command: chown
        owner: sayed
      register: result_chown

    - name: dump output for owner
      debug:
        msg: '{{ result_chown }}'

#    - name: sets group of the hdfs file or directory
#      hdfs_operations:
#        webhdfs_url: http://sandbox.hortonworks.com:50070
#        path: /tmp/kernel_cleaner.sh
#        command: chgrp
#        group: supergroup
#      register: result_chgrp
#
#    - name: dump output for group
#      debug:
#        msg: '{{ result_chgrp }}'

#    - name: sets permissions of the hdfs file or directory
#      hdfs_operations:
#        webhdfs_url: http://sandbox.hortonworks.com:50070
#        path: /tmp/kernel_cleaner.sh
#        command: chmod
#        permission: "0777"
#      register: result_chmod
#
#    - name: dump output for permission
#      debug:
#        msg: '{{ result_chmod }}'

#    - name: creates new directory in hdfs if not exists
#      hdfs_operations:
#        webhdfs_url: http://sandbox.hortonworks.com:50070
#        path: /tmp/some-new
#        command: mkdir
#      register: result_mkdir
#
#    - name: dump output for mkdir
#      debug:
#        msg: '{{ result_mkdir }}'

#    - name: removes file or directory if the hdfs path exists
#      hdfs_operations:
#        webhdfs_url: http://sandbox.hortonworks.com:50070
#        path: /tmp/some-new
#        command: rm
#        recurse: True
#      register: result_rm
#
#    - name: dump output for remove
#      debug:
#        msg: '{{ result_rm }}'

#    - name: uploads a local file to hdfs
#      hdfs_operations:
#        webhdfs_url: http://sandbox.hortonworks.com:50070
#        path: /tmp
#        local_path: /home/sayed/oozie-document-sla-retrieval.adoc
#        command: put
#      register: result_put
#
#    - name: dump output for put
#      debug:
#        msg: '{{ result_put }}'