# playbook defines a set of tasks to be run on hosts.
-
  name: hdfs playbook
  hosts: ubuntu_hosts
  # create tasks
  tasks:
    # Install hdfs python library
    - name: Install hdfs python HDFS client
      become: yes
      pip:
        name: hdfs
        state: latest

    - name: hdfs list directory
      hdfs_ansible:
        webhdfs_host: http://127.0.0.1
        webhdfs_port: 50070
        effective_user: sayed
        hdfsPath: /tmp/
        recurse: False
        command: ls
      register: result

    - debug: var=result